---
resources:

  domains:
    redis: cache.appointment-stage.tb.pro

  tb:network:MultiCidrVpc:
    appointment:
      cidr_block: 10.21.0.0/16
      subnets:
        eu-central-1a:
          - 10.21.0.0/17
        eu-central-1b:
          - 10.21.128.0/17
      enable_internet_gateway: True
      egress_via_internet_gateway: True
      enable_dns_hostnames: True
      endpoint_interfaces:
        - ecr.api
        - ecr.dkr
        - logs
        - secretsmanager
  
  # The __main.py__ here is very specific in the following way:
  # For each ECS cluster you eventually define, you **must** have one entry by the same exact name in the
  # `load_balancers` and `containers` sections below. If the cluster does not expose a service (f/ex, uses
  # `build_load_balancer: False`), you may set the `load_balancers` entry to `null`.
  tb:network:SecurityGroupWithRules:
    load_balancers:
      backend:
        rules:
          ingress:
            - description: TLS traffic to the load balancer from the world
              cidr_blocks:
                - 0.0.0.0/0
              protocol: tcp
              from_port: 443
              to_port: 443
          egress:
            - description: Allow outbound traffic to anywhere
              protocol: tcp
              from_port: 0
              to_port: 65535
              cidr_blocks:
                - 0.0.0.0/0
        
    containers:
      backend:
        rules:
          ingress:
            - description: Allow traffic from the load balancer to the container
              # Sources are set in code
              protocol: tcp
              from_port: 5000
              to_port: 5000
          egress:
            - description: Allow traffic from the container out to the Internet
              protocol: tcp
              from_port: 0
              to_port: 65535
              cidr_blocks:
                - 0.0.0.0/0
    
    other:
      backend_cache:
        rules:
          ingress:
            - description: Primary Redis traffic
              # source_sgs set in code
              protocol: tcp
              from_port: 6379
              to_port: 6379
            - description: Replica Redis traffic
              # source_sgs set in code
              protocol: tcp
              from_port: 6380
              to_port: 6380
          egress:
            - description: Allow outbound traffic to anywhere
              protocol: tcp
              from_port: 0
              to_port: 65535
              cidr_blocks:
                - 0.0.0.0/0
  
  tb:secrets:PulumiSecretsManager:
    pulumi:
      recovery_window_in_days: 0
      secret_names:
        - database-encryption-secret
        - database-host
        - database-name
        - database-password
        - database-user
        - fxa-client-id
        - fxa-secret
        - fxa-openid-config
        - fxa-allow-list
        - fxa-admin-list
        - google-auth-client-id
        - google-auth-secret
        - google-auth-project-id
        - jwt-secret
        - neon-database-connection
        - oidc-client-id
        - oidc-client-secret
        - posthog-project-key
        - session-encryption-secret
        - signed-url-secret
        - smtp-url
        - smtp-username
        - smtp-password
        - x-allow-secret
        - zoom-client-id
        - zoom-auth-secret
        - zoom-api-secret

  tb:ec2:SshableInstance: {}
  # Fill out this template to build an SSH bastion
  # tb:ec2:SshableInstance:
  #   bastion:
  #     ssh_keypair_name: your-ec2-keypair
  #     source_cidrs:
  #       - your.ip.addr.ess/32

  aws:elasticache:ServerlessCache:
    backend:
      description: Appointment backend (stage)
      engine: redis
      major_engine_version: "7"

  tb:fargate:FargateClusterWithLogging:
    backend:
      assign_public_ip: True
      desired_count: 1
      health_check_grace_period_seconds: 30 # Time before the LB checks for health of a new backend
      internal: False
      services:
        backend:
          listener_port: 443
          listener_proto: HTTPS
          listener_cert_arn: arn:aws:acm:eu-central-1:768512802988:certificate/d345f230-258b-4f4f-ae74-6211fd7c234e
          container_port: 5000
          container_name: backend
          # "name" field is arbitrary, but must be unique and no longer than 32 chars
          name: appointment-backend-stage
          health_check:
            healthy_threshold: 2
            unhealthy_threshold: 5
            interval: 30
            path: /
            port: 5000
      task_definition:
        network_mode: awsvpc
        cpu: 512
        memory: 2048
        requires_compatibilities:
          - FARGATE
        container_definitions:
          backend:
            image: 768512802988.dkr.ecr.eu-central-1.amazonaws.com/thunderbird/appointment:743aa79783aac2ac914a8e006ffce80885336fc6
            portMappings:
              - name: backend
                containerPort: 5000
                hostPort: 5000
                protocol: tcp
                appProtocol: http
            linuxParameters:
              initProcessEnabled: True
            secrets:
              # Database connection
              - name: DATABASE_HOST
                valueFrom: arn:aws:secretsmanager:eu-central-1:768512802988:secret:appointment/stage/database-host-cMwTdY
              - name: DATABASE_NAME
                valueFrom: arn:aws:secretsmanager:eu-central-1:768512802988:secret:appointment/stage/database-name-bNiiOY
              - name: DATABASE_USERNAME
                valueFrom: arn:aws:secretsmanager:eu-central-1:768512802988:secret:appointment/stage/database-user-cfbYYI
              - name: DATABASE_PASSWORD
                valueFrom: arn:aws:secretsmanager:eu-central-1:768512802988:secret:appointment/stage/database-password-h8xPx9
              
              # Firefox auth
              - name: FXA_CLIENT_ID
                valueFrom: arn:aws:secretsmanager:eu-central-1:768512802988:secret:appointment/stage/fxa-client-id-YxqZfU
              - name: FXA_SECRET
                valueFrom: arn:aws:secretsmanager:eu-central-1:768512802988:secret:appointment/stage/fxa-secret-w9FcXe
              - name: FXA_OPEN_ID_CONFIG
                valueFrom: arn:aws:secretsmanager:eu-central-1:768512802988:secret:appointment/stage/fxa-openid-config-r1tYME
              - name: FXA_ALLOW_LIST
                valueFrom: arn:aws:secretsmanager:eu-central-1:768512802988:secret:appointment/stage/fxa-allow-list-xrnkYm
              - name: APP_ADMIN_ALLOW_LIST
                valueFrom: arn:aws:secretsmanager:eu-central-1:768512802988:secret:appointment/stage/fxa-admin-list-71QqCa
              - name: POSTHOG_PROJECT_KEY
                valueFrom: arn:aws:secretsmanager:eu-central-1:768512802988:secret:appointment/stage/posthog-project-key-1h1LsO

              # Google OAuth
              - name: GOOGLE_AUTH_CLIENT_ID
                valueFrom: arn:aws:secretsmanager:eu-central-1:768512802988:secret:appointment/stage/google-auth-client-id-AVHrWq
              - name: GOOGLE_AUTH_SECRET
                valueFrom: arn:aws:secretsmanager:eu-central-1:768512802988:secret:appointment/stage/google-auth-secret-CLWZFR
              - name: GOOGLE_AUTH_PROJECT_ID
                valueFrom: arn:aws:secretsmanager:eu-central-1:768512802988:secret:appointment/stage/google-auth-project-id-fotn7G
              
              # OIDC
              - name: OIDC_CLIENT_ID
                valueFrom: arn:aws:secretsmanager:eu-central-1:768512802988:secret:appointment/stage/oidc-client-id-l0LS7y
              - name: OIDC_CLIENT_SECRET
                valueFrom: arn:aws:secretsmanager:eu-central-1:768512802988:secret:appointment/stage/oidc-client-secret-fMpKjV

              # STMP via SocketLabs
              - name: SMTP_URL
                valueFrom: arn:aws:secretsmanager:eu-central-1:768512802988:secret:appointment/stage/smtp-url-HAuJtZ
              - name: SMTP_USER
                valueFrom: arn:aws:secretsmanager:eu-central-1:768512802988:secret:appointment/stage/smtp-username-fWTyya
              - name: SMTP_PASS
                valueFrom: arn:aws:secretsmanager:eu-central-1:768512802988:secret:appointment/stage/smtp-password-A5vsVJ
              
              # Zoom auth
              - name: ZOOM_AUTH_CLIENT_ID
                valueFrom: arn:aws:secretsmanager:eu-central-1:768512802988:secret:appointment/stage/zoom-client-id-npOU9F
              - name: ZOOM_AUTH_SECRET
                valueFrom: arn:aws:secretsmanager:eu-central-1:768512802988:secret:appointment/stage/zoom-auth-secret-eCUX9h
              - name: ZOOM_API_SECRET
                valueFrom: arn:aws:secretsmanager:eu-central-1:768512802988:secret:appointment/stage/zoom-api-secret-Od9vn5

              # Various encryption settings
              - name: DB_SECRET
                valueFrom: arn:aws:secretsmanager:eu-central-1:768512802988:secret:appointment/stage/database-encryption-secret-R0j1vH
              - name: SIGNED_SECRET
                valueFrom: arn:aws:secretsmanager:eu-central-1:768512802988:secret:appointment/stage/signed-url-secret-FMy5P5
              - name: SESSION_SECRET
                valueFrom: arn:aws:secretsmanager:eu-central-1:768512802988:secret:appointment/stage/session-encryption-secret-6EYEm1
              - name: JWT_SECRET
                valueFrom: arn:aws:secretsmanager:eu-central-1:768512802988:secret:appointment/stage/jwt-secret-JKYzbA

            environment:
              - name: APP_ENV
                value: stage
              - name: AUTH_SCHEME
                value: "oidc"
              - name: DATABASE_ENGINE
                value: postgresql
              - name: DATABASE_PORT
                value: '5432'
              - name: FRONTEND_URL
                value: https://appointment-stage.tb.pro
              - name: FXA_CALLBACK
                value: https://appointment-stage.tb.pro/fxa
              - name: GOOGLE_AUTH_CALLBACK_URL
                value: https://appointment-stage.tb.pro/api/v1/google/callback
              - name: JWT_ALGO
                value: "HS256"
              - name: JWT_EXPIRE_IN_MINS
                value: "10000"
              - name: LOG_LEVEL
                value: ERROR
              - name: LOG_USE_STREAM
                value: "True"
              - name: OIDC_EXP_GRACE_PERIOD
                value: "60"
              - name: OIDC_TOKEN_INTROSPECTION_URL
                value: "https://auth-stage.tb.pro/realms/tbpro/protocol/openid-connect/token/introspect"
              - name: POSTHOG_HOST
                value: https://us.i.posthog.com
              - name: REDIS_DB
                value: "0"
              - name: REDIS_PORT
                value: "6379"
              - name: REDIS_URL
                value: cache.appointment-stage.tb.pro
              - name: REDIS_USE_CLUSTER
                value: "True"
              - name: REDIS_USE_SSL
                value: "True"
              - name: SENTRY_DSN
                value: https://5dddca3ecc964284bb8008bc2beef808@o4505428107853824.ingest.sentry.io/4505428124827648
              - name: SERVICE_EMAIL
                value: no-reply@appointment-stage.tb.pro
              - name: SHORT_BASE_URL
                value: https://stage.apt.mt/
              - name: SMTP_PORT
                value: "587"
              - name: SMTP_SECURITY
                value: STARTTLS
              - name: SUPPORT_EMAIL
                value: appointment-support@thunderbird.net
              - name: TIER_BASIC_CALENDAR_LIMIT
                value: "3"
              - name: TIER_PLUS_CALENDAR_LIMIT
                value: "5"
              - name: TIER_PRO_CALENDAR_LIMIT
                value: "10"
              - name: ZOOM_API_ENABLED
                value: "True"
              - name: ZOOM_API_NEW_APP
                value: "False"
              - name: ZOOM_AUTH_CALLBACK
                value: https://appointment-stage.tb.pro/api/v1/zoom/callback

  tb:autoscale:EcsServiceAutoscaler:
    backend:
      cpu_threshold: 80
      ram_threshold: 80
      cooldown: 180
      disable_scale_in: False
      min_capacity: 2
      max_capacity: 4
      suspend: False

  tb:cloudfront:CloudFrontS3Service:
    frontend:
      service_bucket_name: tb-appointment-stage-frontend
      # This cert must be hosted in us-east-1; this limitation is imposed by CloudFront
      certificate_arn: arn:aws:acm:us-east-1:768512802988:certificate/616d9faf-61e0-4d2a-b82d-b1c3d2592052
      distribution:
        aliases:
          - appointment-stage.tb.pro
        comment: Appointment stage frontend
        # Do not define ordered cache behaviors here; they are programmatically overridden
        logging_config:
          include_cookies: True

  tb:cloudwatch:CloudWatchMonitoringGroup:
    cloudwatch:
      notify_emails:
        - thunderbird-services-monitoring@thunderbird.net
      config:
        alarms: {}

  tb:ci:AwsAutomationUser:
    ci:
      access_keys: {}
      enable_legacy_access_key: True
      additional_policies:
        - arn:aws:iam::768512802988:policy/appointment-stage-frontend-cache-invalidation
      enable_ecr_image_push: True
      ecr_repositories:
        - thunderbird/appointment
      enable_fargate_deployments: True
      fargate_clusters:
        - appointment-stage-fargate-backend
      fargate_task_role_arns:
        - arn:aws:iam::768512802988:role/appointment-stage-fargate-backend
      enable_full_s3_access: False
      enable_s3_bucket_upload: True
      s3_upload_buckets:
        - tb-appointment-stage-frontend