---
resources:

  domains:
    redis: cache.appointment.tb.pro

  tb:network:MultiCidrVpc:
    appointment:
      cidr_block: 10.20.0.0/16
      subnets:
        eu-central-1a:
          - 10.20.0.0/17
        eu-central-1b:
          - 10.20.128.0/17
      enable_internet_gateway: True
      egress_via_internet_gateway: True
      enable_dns_hostnames: True
      endpoint_interfaces:
        - ecr.api
        - ecr.dkr
        - logs
        - secretsmanager
  
  # The __main.py__ here is very specific in the following way:
  # For each ECS cluster you eventually define, you **must** have one entry by the same exact name in the
  # `load_balancers` and `containers` sections below. If the cluster does not expose a service (f/ex, uses
  # `build_load_balancer: False`), you may set the `load_balancers` entry to `null`.
  tb:network:SecurityGroupWithRules:
    load_balancers:
      backend:
        rules:
          ingress:
            - description: TLS traffic to the load balancer from the world
              cidr_blocks:
                - 0.0.0.0/0
              protocol: tcp
              from_port: 443
              to_port: 443
          egress:
            - description: Allow outbound traffic to anywhere
              protocol: tcp
              from_port: 0
              to_port: 65535
              cidr_blocks:
                - 0.0.0.0/0
        
    containers:
      backend:
        rules:
          ingress:
            - description: Allow traffic from the load balancer to the container
              # Sources are set in code
              protocol: tcp
              from_port: 5000
              to_port: 5000
          egress:
            - description: Allow traffic from the container out to the Internet
              protocol: tcp
              from_port: 0
              to_port: 65535
              cidr_blocks:
                - 0.0.0.0/0
    
    other:
      backend_cache:
        rules:
          ingress:
            - description: Primary Redis traffic
              # source_sgs set in code
              protocol: tcp
              from_port: 6379
              to_port: 6379
            - description: Replica Redis traffic
              # source_sgs set in code
              protocol: tcp
              from_port: 6380
              to_port: 6380
          egress:
            - description: Allow outbound traffic to anywhere
              protocol: tcp
              from_port: 0
              to_port: 65535
              cidr_blocks:
                - 0.0.0.0/0
  
  tb:secrets:PulumiSecretsManager:
    pulumi:
      recovery_window_in_days: 0
      secret_names:
        - database-encryption-secret
        - database-host
        - database-name
        - database-password
        - database-user
        - fxa-admin-list
        - fxa-allow-list
        - fxa-client-id
        - fxa-openid-config
        - fxa-secret
        - google-auth-client-id
        - google-auth-secret
        - google-auth-project-id
        - jwt-secret
        - oidc-client-id
        - oidc-client-secret
        - posthog-project-key
        - session-encryption-secret
        - signed-url-secret
        - smtp-password
        - smtp-url
        - smtp-username
        - x-allow-secret
        - zoom-api-secret
        - zoom-auth-secret
        - zoom-client-id

  tb:ec2:SshableInstance: {}
  # Fill out this template to build an SSH bastion
  # tb:ec2:SshableInstance:
  #   bastion:
  #     ssh_keypair_name: your-ec2-keypair
  #     source_cidrs:
  #       - your.ip.addr.ess/32

  aws:elasticache:ServerlessCache:
    backend:
      description: Appointment backend (prod)
      engine: redis
      major_engine_version: "7"

  tb:fargate:FargateClusterWithLogging:
    backend:
      assign_public_ip: True
      desired_count: 1
      health_check_grace_period_seconds: 30 # Time before the LB checks for health of a new backend
      internal: False
      services:
        backend:
          listener_port: 443
          listener_proto: HTTPS
          listener_cert_arn: arn:aws:acm:eu-central-1:768512802988:certificate/249fcf3e-0cf2-48ea-b6dc-17239799b3f4
          container_port: 5000
          container_name: backend
          # "name" field is arbitrary, but must be unique and no longer than 32 chars
          name: appointment-backend-prod
          health_check:
            healthy_threshold: 2
            unhealthy_threshold: 5
            interval: 30
            path: /
            port: 5000
      task_definition:
        network_mode: awsvpc
        cpu: 512
        memory: 2048
        requires_compatibilities:
          - FARGATE
        container_definitions:
          backend:
            image: 768512802988.dkr.ecr.eu-central-1.amazonaws.com/thunderbird/appointment:ddd147e76509ede8927a0760572ef3b4a838e738
            portMappings:
              - name: backend
                containerPort: 5000
                hostPort: 5000
                protocol: tcp
                appProtocol: http
            linuxParameters:
              initProcessEnabled: True
            secrets:
              # Databsase connection
              - name: DATABASE_HOST
                valueFrom: arn:aws:secretsmanager:eu-central-1:768512802988:secret:appointment/prod/database-host-jjBGiD
              - name: DATABASE_NAME
                valueFrom: arn:aws:secretsmanager:eu-central-1:768512802988:secret:appointment/prod/database-name-s0pFYu
              - name: DATABASE_PASSWORD
                valueFrom: arn:aws:secretsmanager:eu-central-1:768512802988:secret:appointment/prod/database-password-lrx1wH
              - name: DATABASE_USERNAME
                valueFrom: arn:aws:secretsmanager:eu-central-1:768512802988:secret:appointment/prod/database-user-F5eCXv

              # Firefox auth
              - name: FXA_CLIENT_ID
                valueFrom: arn:aws:secretsmanager:eu-central-1:768512802988:secret:appointment/prod/fxa-client-id-Kw1MOD
              - name: FXA_SECRET
                valueFrom: arn:aws:secretsmanager:eu-central-1:768512802988:secret:appointment/prod/fxa-secret-bVZQ1Q
              - name: FXA_OPEN_ID_CONFIG
                valueFrom: arn:aws:secretsmanager:eu-central-1:768512802988:secret:appointment/prod/fxa-openid-config-FoRyD4
              - name: FXA_ALLOW_LIST
                valueFrom: arn:aws:secretsmanager:eu-central-1:768512802988:secret:appointment/prod/fxa-allow-list-5BMjhF
              - name: APP_ADMIN_ALLOW_LIST
                valueFrom: arn:aws:secretsmanager:eu-central-1:768512802988:secret:appointment/prod/fxa-admin-list-LGZ72H
              - name: POSTHOG_PROJECT_KEY
                valueFrom: arn:aws:secretsmanager:eu-central-1:768512802988:secret:appointment/prod/posthog-project-key-wU9Dyi

              # Google OAuth
              - name: GOOGLE_AUTH_CLIENT_ID
                valueFrom: arn:aws:secretsmanager:eu-central-1:768512802988:secret:appointment/prod/google-auth-client-id-FFp5Se
              - name: GOOGLE_AUTH_SECRET
                valueFrom: arn:aws:secretsmanager:eu-central-1:768512802988:secret:appointment/prod/google-auth-secret-HkUTMA
              - name: GOOGLE_AUTH_PROJECT_ID
                valueFrom: arn:aws:secretsmanager:eu-central-1:768512802988:secret:appointment/prod/google-auth-project-id-1LsMyl

              # OIDC
              - name: OIDC_CLIENT_ID
                valueFrom: arn:aws:secretsmanager:eu-central-1:768512802988:secret:appointment/prod/oidc-client-id-OO2uRC
              - name: OIDC_CLIENT_SECRET
                valueFrom: arn:aws:secretsmanager:eu-central-1:768512802988:secret:appointment/prod/oidc-client-secret-Nhu1bl

              # STMP via SocketLabs
              - name: SMTP_URL
                valueFrom: arn:aws:secretsmanager:eu-central-1:768512802988:secret:appointment/prod/smtp-url-d48icD
              - name: SMTP_USER
                valueFrom: arn:aws:secretsmanager:eu-central-1:768512802988:secret:appointment/prod/smtp-username-hx6dcp
              - name: SMTP_PASS
                valueFrom: arn:aws:secretsmanager:eu-central-1:768512802988:secret:appointment/prod/smtp-password-ItpbDS
              
              # Zoom auth
              - name: ZOOM_AUTH_CLIENT_ID
                valueFrom: arn:aws:secretsmanager:eu-central-1:768512802988:secret:appointment/prod/zoom-client-id-BA59JX
              - name: ZOOM_AUTH_SECRET
                valueFrom: arn:aws:secretsmanager:eu-central-1:768512802988:secret:appointment/prod/zoom-auth-secret-fJa1R1
              - name: ZOOM_API_SECRET
                valueFrom: arn:aws:secretsmanager:eu-central-1:768512802988:secret:appointment/prod/zoom-api-secret-5JqmI2

              # Various encryption secrets
              - name: DB_SECRET
                valueFrom: arn:aws:secretsmanager:eu-central-1:768512802988:secret:appointment/prod/database-encryption-secret-Ozx7B2
              - name: SIGNED_SECRET
                valueFrom: arn:aws:secretsmanager:eu-central-1:768512802988:secret:appointment/prod/signed-url-secret-P75Afi
              - name: SESSION_SECRET
                valueFrom: arn:aws:secretsmanager:eu-central-1:768512802988:secret:appointment/prod/session-encryption-secret-z1Z9wK
              - name: JWT_SECRET
                valueFrom: arn:aws:secretsmanager:eu-central-1:768512802988:secret:appointment/prod/jwt-secret-NrzNnW

            environment:
              - name: APP_ENV
                value: prod
              - name: AUTH_SCHEME
                value: oidc
              - name: DATABASE_ENGINE
                value: postgresql
              - name: DATABASE_PORT
                value: '5432'
              - name: FXA_CALLBACK
                value: https://appointment.day/fxa
              - name: FRONTEND_URL
                value: https://appointment.tb.pro
              - name: GOOGLE_AUTH_CALLBACK
                value: https://appointment.tb.pro/api/v1/google/callback
              - name: JWT_ALGO
                value: "HS256"
              - name: JWT_EXPIRE_IN_MINS
                value: "10000"
              - name: LOG_LEVEL
                value: ERROR
              - name: LOG_USE_STREAM
                value: "True"
              - name: OIDC_EXP_GRACE_PERIOD
                value: "60"
              - name: OIDC_TOKEN_INTROSPECTION_URL
                value: "https://auth.tb.pro/realms/tbpro/protocol/openid-connect/token/introspect"
              - name: POSTHOG_HOST
                value: https://us.i.posthog.com
              - name: REDIS_DB
                value: "0"
              - name: REDIS_PORT
                value: "6379"
              - name: REDIS_URL
                value: cache.appointment.tb.pro
              - name: REDIS_USE_CLUSTER
                value: "True"
              - name: REDIS_USE_SSL
                value: "True"
              - name: SERVICE_EMAIL
                value: no-reply@appointment.tb.pro
              - name: SMTP_PORT
                value: "587"
              - name: SMTP_SECURITY
                value: STARTTLS
              - name: SENTRY_DSN
                value: https://5dddca3ecc964284bb8008bc2beef808@o4505428107853824.ingest.sentry.io/4505428124827648
              - name: SHORT_BASE_URL
                value: https://apt.mt
              - name: SUPPORT_EMAIL
                value: appointment-support@thunderbird.net
              - name: TIER_BASIC_CALENDAR_LIMIT
                value: "3"
              - name: TIER_PLUS_CALENDAR_LIMIT
                value: "5"
              - name: TIER_PRO_CALENDAR_LIMIT
                value: "10"
              - name: ZOOM_API_ENABLED
                value: "True"
              - name: ZOOM_AUTH_CALLBACK
                value: https://appointment.tb.pro/api/v1/zoom/callback
              - name: ZOOM_API_NEW_APP
                value: "False"

  tb:autoscale:EcsServiceAutoscaler:
    backend:
      cpu_threshold: 80
      ram_threshold: 80
      cooldown: 180
      disable_scale_in: False
      min_capacity: 2
      max_capacity: 4
      suspend: False

  tb:cloudfront:CloudFrontS3Service:
    frontend:
      service_bucket_name: tb-appointment-prod-frontend
      # This cert must be hosted in us-east-1; this limitation is imposed by CloudFront. It must
      # also cover both the normal and short URL domains.
      certificate_arn: arn:aws:acm:us-east-1:768512802988:certificate/1bf9a946-e840-4c70-a726-19865db25a2f
      distribution:
        aliases:
          - appointment.tb.pro
          - apt.mt
        comment: Appointment prod frontend
        # Do not define ordered cache behaviors here; they are programmatically overridden
        logging_config:
          include_cookies: True

  tb:cloudwatch:CloudWatchMonitoringGroup:
    cloudwatch:
      notify_emails:
        - thunderbird-services-monitoring@thunderbird.net
      config:
        alarms: {}

  tb:ci:AwsAutomationUser:
    ci:
      access_keys: {}
      enable_legacy_access_key: True
      additional_policies:
        - arn:aws:iam::768512802988:policy/appointment-prod-frontend-cache-invalidation
      enable_ecr_image_push: True
      ecr_repositories:
        - thunderbird/appointment
      enable_fargate_deployments: True
      fargate_clusters:
        - appointment-prod-fargate-backend
      fargate_task_role_arns:
        - arn:aws:iam::768512802988:role/appointment-prod-fargate-backend
      enable_full_s3_access: False
      enable_s3_bucket_upload: True
      s3_upload_buckets:
        - tb-appointment-prod-frontend