name: deploy-staging-and-create-release

concurrency:
  group: deploy-staging
  cancel-in-progress: true

on:
  push:
    branches:
      - main

permissions:
  id-token: write # required for OIDC connecting to AWS
  contents: write # This is required to create a release

jobs:
  build-and-deploy-stage-frontend:
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-central-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_PULUMI }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_PULUMI }}
      
      - name: Setup NPM
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: cd frontend && npm install

      - name: Build stage frontend
        run: |
          rm -rf frontend/dist  # Clean up from previous build
          cp frontend/.env.pulumistage.example frontend/.env.stage
          cd frontend && npm run build -- --mode ${{ vars.APP_ENV }}

      - name: Deploy frontend to S3
        run: |
          aws s3 sync frontend/dist s3://${{ secrets.FRONTEND_BUCKET }}
          aws cloudfront create-invalidation --distribution-id ${{ secrets.FRONTEND_CF_DISTRO_ID }} --paths '/*'

  build-backend-image:
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials (Pulumi)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-central-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_PULUMI }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_PULUMI }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: 'true'

      - name: Build, tag, and push backend image to Amazon ECR
        id: build-backend
        env:
          ECR_TAG: '${{ steps.login-ecr.outputs.registry }}/thunderbird/appointment:${{ github.sha }}'
          RELEASE_VERSION: ${{ github.sha }}
        run: |
          # Build a docker container and
          # push it to ECR so that it can
          # be deployed to ECS.
          docker build --build-arg "RELEASE_VERSION=$RELEASE_VERSION" -t $ECR_TAG ./backend -f ./backend/Dockerfile
          docker push $ECR_TAG
          echo "image_backend=$ECR_TAG" >> $GITHUB_OUTPUT
          echo $ECR_TAG > new_ecr_tag.txt

      - name: Archive ECR tag
        uses: actions/upload-artifact@v4
        with:
          name: new_ecr_tag
          path: new_ecr_tag.txt

  deploy-stage-backend:
    needs:
      - build-backend-image
    if: needs.build-backend-image.result == 'success'
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download ecr tag
        uses: actions/download-artifact@v4
        with:
            name: 
              new_ecr_tag

      - name: Configure AWS credentials for Pulumi
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-central-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_PULUMI }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_PULUMI }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: "true"

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Unpack ECR tag
        id: get_ecr_tag
        run: |
          output=$(cat new_ecr_tag.txt)
          echo new_ecr_tag=$output >> $GITHUB_OUTPUT

      # Deploy to stage
      - name: Deploy new image to stage
        shell: bash
        env:
          ECR_TAG: "${{ steps.get_ecr_tag.outputs.new_ecr_tag }}"
          PULUMI_ACCESS_TOKEN: "${{ secrets.PULUMI_ACCESS_TOKEN }}"
        run: |
          # Update the PATH to include the right version of Pulumi; this is non-trivial or impossible
          # to do with the GHA workflow "env" settings above.
          export PATH="/home/runner/.pulumi/bin:$PATH"

          cd pulumi

          # Create a YAML config stump containing only the nested tree leading to the image tag update
          cat << EOF > newimage.yaml
          resources:
            tb:fargate:FargateClusterWithLogging:
              backend:
                task_definition:
                  container_definitions:
                    backend:
                      image: "$ECR_TAG"
          EOF

          # Use yq to merge the stump into the main config
          yq -i '. *= load("newimage.yaml")' config.stage.yaml

          # Set up the Pulumi environment and update the service
          export PULUMI_CONFIG_PASSPHRASE="${{ secrets.PULUMI_PASSPHRASE }}"
          pulumi login
          pulumi stack select stage
          pulumi up -y --diff --target \
            'urn:pulumi:stage::appointment::tb:fargate:FargateClusterWithLogging$aws:ecs/taskDefinition:TaskDefinition::appointment-stage-fargate-backend-taskdef' \
            --target-dependents

  create-release:
    needs:
      - build-backend-image
      - build-and-deploy-stage-frontend
      - deploy-stage-backend
    if: |
      always() &&
      contains(join(needs.*.result, ','), 'success') &&
      ! contains(join(needs.*.result, ','), 'failure')
    environment: production
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup NPM
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: cd frontend && npm install

      - name: Build prod frontend
        run: |
          cp frontend/.env.prod.example frontend/.env.prod
          cd frontend && npm run build -- --mode ${{ vars.APP_ENV }}
          zip -r ../frontend.zip dist

      - name: Download ECR tag
        uses: actions/download-artifact@v4
        with:
            name: 
              new_ecr_tag
      
      - name: Zip Pulumi
        run: |
          # Remove any lingering build pieces that may exist
          pushd pulumi
          rm -rf appointment_pulumi.egg-info build __pycache__ .ruff_cache venv
          popd

          # Tarbizz the Pulumi IaC
          tar -cvjf pulumi.tbz pulumi/

      - name: Create release tag
        id: create-release-tag
        run: echo "tag_name=r-$(printf %04d $GITHUB_RUN_NUMBER)" >> $GITHUB_OUTPUT

      - name: Create draft release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.create-release-tag.outputs.tag_name }}
          name: Release ${{ steps.create-release-tag.outputs.tag_name }}
          body: |
            ## Info
            Commit ${{ github.sha }} was deployed to `stage`. [See code diff](${{ github.event.compare }}).

            It was initialized by [${{ github.event.sender.login }}](${{ github.event.sender.html_url }}).

            ## How to Promote?
            In order to promote this to prod, edit the draft and press **"Publish release"**.
          draft: true
          files: |
            new_ecr_tag.txt
            frontend.zip
            pulumi.tbz

  e2e-tests-browserstack-stage:
    name: e2e-tests-browserstack-stage
    needs: create-release
    if: false
    # if: ${{ !failure() || !cancelled() }}
    runs-on: ubuntu-latest
    environment: staging
    env:
      APPT_LOGIN_EMAIL: ${{ secrets.E2E_APPT_STAGE_LOGIN_EMAIL }}
      APPT_LOGIN_PWORD: ${{ secrets.E2E_APPT_STAGE_LOGIN_PASSWORD }}
      APPT_DISPLAY_NAME: ${{ secrets.E2E_APPT_STAGE_DISPLAY_NAME }}
      APPT_MY_SHARE_LINK: ${{ secrets.E2E_APPT_STAGE_MY_SHARE_LINK }}
      APPT_BOOKEE_EMAIL: ${{ secrets.E2E_APPT_STAGE_BOOKEE_EMAIL }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: 'test/e2e/package-lock.json'

      - name: Install dependencies
        run: |
          cd ./test/e2e
          npm install

      - name: BrowserStack Env Setup
        uses: browserstack/github-actions/setup-env@master
        with:
          username:  ${{ secrets.BROWSERSTACK_USERNAME }}
          access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
          project-name: 'Thunderbird Appointment'
          build-name: 'E2E Tests: BUILD_INFO'

      - name: Run E2E Tests on stage via Browserstack
        run: |
          cd ./test/e2e
          cp .env.stage.example .env
          npm run e2e-test-browserstack-gha

