name: IaC Main

on:
  push:

env:
  tf_version: '1.6.2'
  tg_version: '0.55.15'
  aws_region: us-east-1

jobs:
  verify:
    if: github.ref != 'refs/heads/main'
    strategy:
      matrix:
        environment: [stage, production]
        module: [terraform/tfbackend, network/vpc, services/backend-infra, data-store/cache, data-store/database, services/frontend]
    uses: ./.github/workflows/iac_verify.yaml
    with:
      tf_version: env.tf_version
      tg_version: env.tg_version
      aws_region: env.aws_region
      environment: matrix.envrionment
      module: matrix.module
    secrets: inherit

  apply:
    if: github.ref == 'refs/heads/main'
    strategy:
      matrix:
        environment: [stage]
        module: [terraform/tfbackend, network/vpc, services/backend-infra, data-store/cache, data-store/database, services/frontend]
    uses: ./.github/workflows/iac_apply.yaml
    with:
      tf_version: env.tf_version
      tg_version: env.tg_version
      aws_region: env.aws_region
      environment: matrix.envrionment
      module: matrix.module
    secrets: inherit

