name: validate-iac
on: 
  push:
  workflow_call:
env:
  tf_version: '1.6.2'
  tg_version: '0.55.15'
  environment: 'stage'

jobs:
  validate-iac:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: opentofu/setup-opentofu@v1
        with: 
          tofu_version: ${{ env.tf_version }}
      - run: |
          git clone --depth 1 --branch main https://github.com/tgenv/tgenv.git ~/.tgenv
          sudo ln -s ~/.tgenv/bin* /usr/local/bin
          tgenv install ${{ env.tg_version }}
      - run: |
          cd ./tofu/environments/${{ env.environment }}/terraform/tfbackend
          terragrun init
          terragrunt validate

