name: IaC Main

concurrency:
  group: iac
  cancel-in-progress: true

on:
  push:

permissions:
  id-token: write
  contents: read

env:
  TF_VERSION: '1.6.2'
  TG_VERSION: '0.55.15'
  AWS_REGION: us-east-1

jobs:
  iac-changes:
    runs-on: ubuntu-latest
    outputs:
      run-iac: ${{ steps.check.outputs.run-iac }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: check
        with:
          filters: |
            run-iac:
              - 'tofu/**'
              - '.github/workflows/**'

  verify:
    needs: iac-changes
    if: github.ref != 'refs/heads/main' && needs.iac-changes.outputs.run-iac == 'true'
    strategy:
      max-parallel: 1
      matrix:
        environment: [stage, production]
    uses: ./.github/workflows/iac_verify.yaml
    with:
      tf_version: 1.6.2
      tg_version: 0.55.15
      aws_region: us-east-1
      environment: ${{ matrix.environment }}
    secrets: inherit

  apply:
    needs: iac-changes
    if: github.ref == 'refs/heads/main' && needs.iac-changes.outputs.run-iac == 'true'
    strategy:
      max-parallel: 1
      matrix:
        environment: [stage]
    uses: ./.github/workflows/iac_apply.yaml
    with:
      tf_version: 1.6.2
      tg_version: 0.55.15
      aws_region: us-east-1
      environment: ${{ matrix.environment }}
    secrets: inherit

