name: validate-iac
on: 
  push:
  workflow_call:
env:
  tf_version: '1.6.2'
  tg_version: '0.55.15'
  environment: 'stage'

jobs:
  validate-iac:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install opentofu
        uses: opentofu/setup-opentofu@v1
        with: 
          tofu_version: ${{ env.tf_version }}
      - name: install terragrunt
        run: |
          sudo wget -q -O /bin/terragrunt "https://github.com/gruntwork-io/terragrunt/releases/download/v${{ env.tg_version }}/terragrunt_linux_amd64"
          sudo chmod +x /bin/terragrunt
          terragrunt -v
      - name: validate
        run: |
          cd ./tofu/environments/${{ env.environment }}/terraform/tfbackend
          terragrunt init
          terragrunt validate

